dataset:
  train:
    name: mixed
    prob_ls: [0.9, 0.1]
    dataset_list:
    - name: hypersim_depth
      disp_name: hypersim_depth_train
      dir: hypersim_preprocessed/train #hypersim_processed_train.tar
      filenames: data_split/hypersim_depth/filename_list_train_filtered.txt
      resize_to_hw:
      - 768 #480
      - 1024 #640
    - name: vkitti_depth
      disp_name: vkitti_depth_train
      dir: virtual_kitti2
      filenames: data_split/vkitti_depth/vkitti_train.txt
      resize_to_hw:
      - 768
      - 1024
      kitti_bm_crop: true
      valid_mask_crop: null
